### ISSUE TITLE
sportkanalen.se is empty from 2020-03-07 and onwards

### ISSUE THREAD

**Issue by jnylen** [xmltv-se/issues#1]
## Channel XMLTV ID

sportkanalen.se

## Specific date

2020-03-07 and onwards

from Gitlab

**Comment by skoglump** [comment]
It seems that the problem is not limited to sportkanalen.se but is affecting all channels from cmore (which sportkanalen is a part of)

**Comment by jnylen** [comment]
Should be fixed.
