### ISSUE TITLE
tv_grab_se_tvzon / closing tag

### ISSUE THREAD

**Issue by itchykill** [xmltv-se/issues#12]
When generating output XML file with tv_grab_se_tvzon there is an error in the file.
Debug says there's a wrong closing tag at the last line. The closing tag is < / tv >
Exact error message in xteve:

XML syntax error on line 763831: element < actor > closed by < / tv >

@jnylen 
:-)

**Comment by jnylen** [comment]
@itchykill try to remove all of the cache for xmltv in `~/.xmltv` and fetch the data again.
If it still occurs, send me the airing that it happens to. This has been reported multiple times but it has always ended up being either that the files didn't fully download or the script crashed and just cached an incomplete download.

**Comment by itchykill** [comment]
@jnylen You were right. It works. Thanks!

Tak for hjælpen :-)
