### ISSUE TITLE
India Channel EPG

### ISSUE THREAD

**Issue by vimz99** [xmltv-se/issues#17]
[India.tv.channels.zip](https://github.com/xmltv-se/issues/files/4357413/India.tv.channels.zip)

I've attached webgrab+ xml file for epg of Indian channels. Would be great if you can add them to your service.

**Comment by jnylen** [comment]
@vimz99 I think you have missunderstood what XMLTV.se does.

We don't fetch data from other tvguide websites, we get them from the channels themselves. Please create one issue per channel/channel owner with the Channel request issue template.
