### ISSUE TITLE
Some gaps in Swedish channels

### ISSUE THREAD

**Issue by jnylen** [xmltv-se/issues#2]
## Channel XMLTV ID

*  kanal5.se
*  kanal9.se

## Specific date

times in CET

Kanal 5:
*  2020-02-22 20:00 - 2020-02-22 21:00
*  2020-02-22 23:33 - 2020-02-23 00:04
*  2020-02-23 04:35 - 2020-02-23 05:17
*  2020-02-23 21:00 - 2020-02-23 21:32
*  2020-02-24 01:01 - 2020-02-24 01:55
*  2020-02-24 19:33 - 2020-02-24 19:59
*  2020-02-24 23:02 - 2020-02-25 00:04
*  2020-02-25 23:03 - 2020-02-26 00:04

Kanal 9:
*  2020-02-22 05:14 - 2020-02-22 05:38
*  2020-02-22 11:56 - 2020-02-22 12:55

Week 10:
* fakta.tv4.se 2020-03-04 21:09 2020-03-04 22:07
* fakta.tv4.se 2020-03-05 02:58 2020-03-05 04:00
* fakta.tv4.se 2020-03-05 07:01 2020-03-05 08:00
* film.tv4.se 2020-03-08 18:49 2020-03-08 21:00
* tv11.sbstv.se 2020-03-07 08:21 2020-03-07 09:24

**Comment by anders55j** [comment]
Some findings the coming days. Some of these should have a special character in the title, like a colon or an exclamation mark. I don't know if it is a coincidence or not.

- fakta.tv4.se 2020-03-28 21:51	2020-03-28 23:00
- fakta.tv4.se 2020-03-29 03:00	2020-03-29 04:03
- fakta.tv4.se 2020-03-29 05:00	2020-03-29 06:00
- fakta.tv4.se 2020-03-29 22:00	2020-03-29 23:00
- fakta.tv4.se 2020-03-30 01:59	2020-03-30 03:00
- tv11.sbstv.se 2020-03-29 22:40 2020-03-29 23:35
- tv11.sbstv.se 2020-03-28 22:04 2020-03-28 23:12
- kanal5.se 2020-03-30 04:56 2020-03-30 05:37
- kanal5.se 2020-03-30 21:00 2020-03-30 22:00

**Comment by anders55j** [comment]
Probably the worst week so far:
TV4:
tv4.se	2020-04-25 17:59	2020-04-25 19:00
tv4.se	2020-04-27 13:59	2020-04-27 15:00
tv4.se	2020-04-27 23:28	2020-04-27 23:57
sjuan.se	2020-04-28 01:02	2020-04-28 02:00
sjuan.se	2020-04-28 21:59	2020-04-28 23:00
tv4.se	2020-04-28 23:28	2020-04-28 23:57
tv4.se	2020-04-29 20:59	2020-04-29 22:00
tv4.se	2020-04-29 23:28	2020-04-29 23:57
sjuan.se	2020-05-01 01:02	2020-05-01 02:02
tv4.se	2020-05-01 01:09	2020-05-01 03:29
Discovery:
kanal5.se	2020-04-25 16:58	2020-04-25 18:00
kanal9.se	2020-04-25 18:52	2020-04-25 19:58
kanal5.se 2020-04-26 02:06	2020-04-26 02:55
kanal5.se 2020-04-26 20:00	2020-04-26 21:00
tv11.sbstv.se 2020-04-26 21:56	2020-04-26 22:56
kanal5.se 2020-04-27 21:00	2020-04-27 22:00
kanal9.se	2020-04-28 14:56	2020-04-28 15:26
kanal5.se 2020-04-28 21:00	2020-04-28 22:00
tv11.sbstv.se 2020-04-29 19:58	2020-04-29 21:00
kanal5.se 2020-04-30 04:15	2020-04-30 04:56
tv11.sbstv.se 2020-05-01 19:58	2020-05-01 21:00

**Comment by anders55j** [comment]
I assume #104 has been deployed, but it didn't seem to help. I checked the last week available (May 18 - May 24) and there are still gaps present (times in CEST):
hd.tv4.se	2020-05-18 20:00	2020-05-18 21:00
hd.tv4.se	2020-05-24 20:00	2020-05-24 21:00
fakta.tv4.se	2020-05-24 22:00	2020-05-24 23:00
sjuan.se	2020-05-22 13:00	2020-05-22 14:00
sjuan.se	2020-05-24 06:00	2020-05-24 07:00
kanal5.se	2020-05-19 21:00	2020-05-19 22:05
kanal5.se	2020-05-23 18:55	2020-05-23 20:00
kanal5.se	2020-05-23 23:20	2020-05-24 00:30
kanal5.se	2020-05-24 19:55	2020-05-24 21:00
tv11.sbstv.se	2020-05-24 22:30	2020-05-24 23:30

**Comment by jnylen** [comment]
@anders55j can you check now?

**Comment by anders55j** [comment]
All gaps from my previous comment is still there I'm afraid.

**Comment by jnylen** [comment]
@anders55j,
If you can check again today (I force exported everything after the drives were full). It looked fixed in my development environment) then I can try to look into it today as I have some time over today.

I noticed one empty spot on tv11.sbstv.se 2020-05-24 20:30-21:30, so I guess all of the issues that you listed in that comment are still correct?

Is your times in UTC or UTC+2?

**Comment by anders55j** [comment]
Sorry, my times are in UTC+2. All gaps are still there in the new files.

**Comment by jnylen** [comment]
@anders55j does this happen with the SVT channels? They use the same parser. But those you listed hits a different API (but the same api for all of them) while SVT sends files by FTP.

**Comment by anders55j** [comment]
No, I've never seen this issue on SVT.

**Comment by Neoand2** [comment]
There are still gaps every now and then. 

Examples of empty slots:

tv4.se 2020-jun-05 20:00 - 22:00 
tv4.se 2020-jun-05 22:15 - 22:40 
tv4.se 2020-jun-06 20:00 - 22:00 
tv4.se 2020-jun-07 20:00 - 21:00 
tv4.se 2020-jun-12 20:00 - 22:00 
tv4.se 2020-jun-14 20:00 - 21:00 

kanal5.se 2020-jun-07 20:00 - 21:00 

tv11.sbstv.se 2020-jun-06 22:00 - 23:00 
tv11.sbstv.se 2020-jun-07 22:15 - 23:20

**Comment by jnylen** [comment]
Fixed, should be up2date tomorrow.

**Comment by Neoand2** [comment]
Great! Thank you

**Comment by anders55j** [comment]
Much better now! Thank You! I still see two gaps but I'm pretty sure that is another issue, if it happens more times I will add a new issue for that.
