### ISSUE TITLE
Using the data?

### ISSUE THREAD

**Issue by tanghus** [xmltv-se/issues#22]
This is probably not the right forum, but I couldn't find anywhere else.

Firstly, on [your web site](https://xmltv.se/) it says:

> ## How to use
>
> Please see the guides folder for how to use it in different OS:es etc.

But I can't find any guides folder.

### Background:

I have written a Danish TV Guide app for [Sailfish OS](https://sailfishos.org/) mainly to
scratch my own itch. It currently uses an unauthorized API so I haven't officially released it.
Over time the app has improved, so I'm looking for alternative data sources so that other
Sailfish OS users could make use of it. I have no intentions whatsoever to try to take money for it btw.

The TL;DR: Have I come to the right place? I have a **LOT** of questions if so,
but it would be wasting every ones time if not :)

![Screenshot_20200506_001](https://user-images.githubusercontent.com/533222/81177538-1dc54780-8fa7-11ea-94b8-88de75af8d6d.png)

![Screenshot_20200506_007](https://user-images.githubusercontent.com/533222/81177822-90362780-8fa7-11ea-9226-4d9fcf67210a.png)

![Screenshot_20200506_009](https://user-images.githubusercontent.com/533222/81177882-a47a2480-8fa7-11ea-97f9-89c9145efdcc.png)

![Screenshot_20200506_002](https://user-images.githubusercontent.com/533222/81177633-44837e00-8fa7-11ea-850a-5ccab6491b6d.png)

![Screenshot_20200506_003](https://user-images.githubusercontent.com/533222/81177654-52390380-8fa7-11ea-879a-1f8baa0b415a.png)

![Screenshot_20200506_004](https://user-images.githubusercontent.com/533222/81177701-6250e300-8fa7-11ea-8a50-5582e2255841.png)

![Screenshot_20200506_005](https://user-images.githubusercontent.com/533222/81177710-6846c400-8fa7-11ea-98e1-aeb7860b7c7a.png)

![Screenshot_20200506_006](https://user-images.githubusercontent.com/533222/81177722-6da40e80-8fa7-11ea-9323-4ae2869606ad.png)

**Comment by jnylen** [comment]
What you are looking for is https://honeybee.it/api

**Comment by tanghus** [comment]
Thanks, but my pension doesn't have room for that.
