### ISSUE TITLE
Errors in XML file.

### ISSUE THREAD

**Issue by rco133** [xmltv-se/issues#23]
Hi.

I am having problems using the XML data downloaded by tv_grab_se_tvzon. I have also tried XMLTV 0.6.1 using tv_grab_eu_xmltvse and the problem is the same there.

Right now it is working if I only download 2 days worth of data. If I download 3 days worth of data, I can't import the XML file.

I have tested the 2 day file in several online XML validators, and that file checks out fine in all of them. The 3 day file comes back with an error like this:

error on line 27824 at column 6: Opening and ending tag mismatch: sub-title line 0 and tv

Line 27824 is the last line containing just </tv>

In the 3 day file I have found at least one line starting with <desc> and not ending with </desc>. I have tried to edit that line manually, but still can't import the file. There might be more places where a line with <> is not ended with </>. Not sure how to find them though.

I found another line, this time <sub-title> without and ending </sub-title>, and now the file can be imported. There seems to be some problem with some <> not having their </> counterpart.

I found a previous bug report suggesting to empty the cache folder, and I have done that many times today, and it doesn't change anything.

Hm, I can see that some of the stuff I write isn't shown. The lines I have found are desc and sub-title missing the end / part.

Additional info. Have now searched through a 10 day XML file. I found 4 lines with start desc and no end /desc. All the issues were in the dk4 channel file. The desfription is just interupted at some random place in the line, and then a "<programme channel="dr1.dr.dk"...." comes in the middle of it all.

Thansk in advance.

**Comment by jnylen** [comment]
Fixed. Regenerating data. Should pop up soon. We had a full harddrive.

**Comment by dkrasmussen** [comment]
hi, 

now i got this problem
using tv_grab_eu_xmltvse

from my xmltv.xml file
...
</programme\>
<prog \<programme channel="bbcworldnews.com" start="20200705040000 +0000" stop="20200705043000 +0000">
...

and from my mythfilldatabase
2020-07-05 13:59:50.729841 I  Starting IO manager (write)
2020-07-05 13:59:50.950479 E  Error in 7782:5: tag mismatch
2020-07-05 13:59:50.961840 I  No programs found in data.


/Dennis
