### ISSUE TITLE
dk4.dk - invalid xml in .gz files

### ISSUE THREAD

**Issue by kibuan** [xmltv-se/issues#26]
**Channel XMLTV ID**
dk4.dk

**Specific date**
10/5-2020 - http://xmltv.xmltv.se/dk4.dk_2020-05-10.xml.gz
12/5-2020 - http://xmltv.xmltv.se/dk4.dk_2020-05-12.xml.gz
13/5-2020 - http://xmltv.xmltv.se/dk4.dk_2020-05-13.xml.gz
16/5-2020 - http://xmltv.xmltv.se/dk4.dk_2020-05-16.xml.gz
17/5-2020 - http://xmltv.xmltv.se/dk4.dk_2020-05-17.xml.gz
19/5-2020 - http://xmltv.xmltv.se/dk4.dk_2020-05-19.xml.gz
20/5-2020 - http://xmltv.xmltv.se/dk4.dk_2020-05-20.xml.gz
21/5-2020 - http://xmltv.xmltv.se/dk4.dk_2020-05-21.xml.gz

didn't test more...

The .gz files are faulty. They seem to be "cut off". The corresponding .xml files are properly formatted. Only the .gz files are invalid.

**Comment by jnylen** [comment]
Fixed. Regenerating data. Should pop up soon. We had a full harddrive.
