### ISSUE TITLE
Missing channels-TV.xml.gz file

### ISSUE THREAD

**Issue by kibuan** [xmltv-se/issues#27]
When I run:

tv_grab_eu_xmltv.se --configure

After selecting: "15: All tv channels" I get this:

"Failed to fetch http://xmltv.xmltv.se/channels-TV.xml.gz at /usr/local/bin/tv_grab_eu_xmltvse line 400."

If selecting "2: Denmark" I get:

"Failed to fetch http://xmltv.xmltv.se/channels-Denmark.xml.gz at /usr/local/bin/tv_grab_eu_xmltvse line 400."

It seems like some files are missing in http://xmltv.xmltv.se/

**Comment by jnylen** [comment]
Yeah, sorry about that. We removed all files and exported them again. The queue got too big as it was importing files at the same times.

So it was a queue of 2400+ exports.

Should be fine now @kibuan.

**Comment by kibuan** [comment]
No worries. Thank you for fixing it 👍😊
