### ISSUE TITLE
news.tv2.dk Data stopped from 28/6 and forward

### ISSUE THREAD

**Issue by oj48** [xmltv-se/issues#31]
**Channel XMLTV ID**

Example: svt1.svt.se

**Specific date**

Only provided if it's a specific date only.

**Comment by anders55j** [comment]
And also other tv2.dk-channels from 2020-07-06 and onwards

**Comment by jnylen** [comment]
@anders55j fixed.

@oj48 next time please provide an complete description rather than just in the title in the future.
