### ISSUE TITLE
No data after 04-Jul on http://xmltv.xmltv.se/

### ISSUE THREAD

**Issue by JD906** [xmltv-se/issues#32]
No data for any channels, after 04-jul on http://xmltv.xmltv.se/

**Comment by jnylen** [comment]
@JD906 there is data.
Which channels are you talking about?

**Comment by JD906** [comment]
Sorry, maybe I looked at it wrong, is the date and timestamp in the middle, when it is created or updated?
https://gyazo.com/4b9cdcf6b3f727e747cc0872fe865442

Anyways, noticed the data for zulu.tv2.dk was all wrong today, thats why I started looking at it.
So the data is wrong for that channel. (haven't checked others)

Also there is only data for a few days, is that the new 3 day limit?

**Comment by jnylen** [comment]
@JD906 so the listing is just a normal HTTP Server list.
The datetime there is the last time the file was modified.

What you should look at is the numbers on the right. if its below 150 then there is no data.

I ran a force update on TV2 DK channels and i'll go through other channels to fix the data there. Been busy alot the past 6 months. But now got a vacation time for a month so i'll try to finish most projects.

**Comment by JD906** [comment]
Got it, thx.. :)

**Comment by jnylen** [comment]
@JD906 Data should be there now. If some days are missing it probably due to cache and should be back tomorrow.
