### ISSUE TITLE
tv11.sbstv.se - are overlapping programmes being removed?

### ISSUE THREAD

**Issue by anders55j** [xmltv-se/issues#34]
**Channel XMLTV ID**

tv11.sbstv.se

**Specific date**

2020-07-12

**Example**

I've seen this issue on dplay channels a few times since #2 was fixed. [The official schedule](https://www.dplay.se/tv-guide) has one program 12:15-12:45 and another 12:40-13:10. http://xmltv.xmltv.se/tv11.sbstv.se_2020-07-12.xml lacks the second of those. Maybe this caused too #2 too. I can see this being a feature in some cases but maybe some more logic is required. I would prefer overlapping programmes myself in this case but I don't know about other clients.

**Comment by jnylen** [comment]
@anders55j they will be if an `end_time` is provided. Clipsource importer does not use these due to the issues you supply here.

The XML file matches up with the tvguide on their website. So unsure what you are talking about.
If they overlap the the end time will be changed to match the start_time of the next airing. As we can't have overlapping airings due to the XMLTV dtd.

**Comment by anders55j** [comment]
My example seems to fixed in some way, but there is another gap one between 20200716145500 and 20200716152500 GMT in http://xmltv.xmltv.se/tv11.sbstv.se_2020-07-16.xml.  [The official schedule](https://www.dplay.se/tv-guide) has an overlap 16:50-1655 CEST. Can't be a coincidence that the gaps always has an overlap in the official schedule but I don't know where issue is.

By the way, fixing endtime sounds like a good way to handle overlaps given the DTD requirements, if I make a recording I always add some minutes anyway.

**Comment by jnylen** [comment]
@anders55j do you have more days of this?
Easier to track down as if I only see one day it can just be a mishap.

**Comment by anders55j** [comment]
The coming gaps are far away so I don't have any other schedule to compare with. All are on TV11. Timezone is CEST.
2020-07-28 07:05-2020-07-28 07:25
2020-07-31 17:00-2020-07-31 17:30
2020-08-01 08:05-2020-08-01 09:00
2020-08-01 18:00-2020-08-01 18:55
2020-08-05 17:00-2020-08-05 17:30

**Comment by jnylen** [comment]
@anders55j I noticed the issue only on the 31/07.
The issue of the missing Sister Wives is this:
The airing before the Sister Wives on 15:00 (UTC) ends on 15:00 while that specific Sister Wives airing starts on 14:55 (UTC) but is listed as airing after. And as we do checks when we add airings on whether it looks like a reliable datetime as we don't want duplicates passing over eachother this airing gets skipped.

What I can do is comment out end time for Clipsource until they fix it on their side, alternatively add a check that updates the start time etc but that will take a lot of time as the parse is a streaming one as we don't wanna put the whole file in memory. [1] The parser is used by Discovery (SE, DK), SVT, NENT (all), Viasat Hungry (SONY TV), CMore/TV4.

I'm emailing them about the issue.

[1] https://github.com/xmltv-se/vind/blob/master/apps/importer/lib/importer/parser/public_schedule.ex#L900

**Comment by anders55j** [comment]
Ok, I think I understand. 

Not sure about the temporary fix though. What happens at night if there is no airing? Isn't there a risk that is filled up by the last programme?
