### ISSUE TITLE
much channels do not have data

### ISSUE THREAD

**Issue by kaiontour** [xmltv-se/issues#39]
channels in Germany like das erste, bundesliga 1-10 and other do not have epg data. when I look to xmltv.xmltv.se I see the files are only a few kb

one example: das erste
5.9.20 is ok, but starting 6.9.20 all is in:
<tv generator-info-name="Vind" generator-info-url="https://xmltv.se"/>

**Comment by jnylen** [comment]
Hi,
It's because we did a change how we handle incoming files. So we upload these to the cloud. And currently these does not exist there her and it's still processing all of them. It's 400+ GB of files that needs to be transferred.

Please wait for a bit and it should pop up soon.

**Comment by jnylen** [comment]
Hi again @kaiontour,
They should be popping in now again.
Has to do some changes in how I handle incoming files via ftp and email so took a bit of time.

Ping me if any channel doesn't have data by today's lunch.

**Comment by anders55j** [comment]
Hi, I'm still missing natgeo.se

**Comment by jnylen** [comment]
@anders55j on it's way up.

**Comment by jnylen** [comment]
Closing this, data will be coming in during the day. Fixed an issue where the new way of handling incoming files ruined that importer as we fetch the data from the cloud now (where we store all the files) but were pointing the file_read on the wrong variable.

If any other channels are having issues please open a new issue.
