### ISSUE TITLE
Sky Deutschland - Misisng Data

### ISSUE THREAD

**Issue by repbug** [xmltv-se/issues#40]
sport1.sky.de

**Comment by jnylen** [comment]
@repbug 
Sorry been busy. I'll look into this later today.

**Comment by jnylen** [comment]
@repbug 
Hi again, sorry for late fix on this. The issue was that Sky for whatever reason decided to add an extra space between `Sky Sport` and `1` so it became `Sky Sport  1` rather than `Sky Sport 1`.

This should now be fixed by tomorrow.
