### ISSUE TITLE
svt1,svt2 etc Sverige saknar data 

### ISSUE THREAD

**Issue by mactba** [xmltv-se/issues#41]
**Channel XMLTV ID
svt1.svt.se etc saknar data 
Har bara hittat kanal 9 i listan 

**Specific date**
All data saknas på svt1,svt2,tv3 etc

**Comment by mactba** [comment]
More info From 28/9 and forward and this is for svt1,svt2.tv3,tv4 etc

**Comment by jnylen** [comment]
Read #21
