### ISSUE TITLE
all xml Files have no data after 27 sept since a few days

### ISSUE THREAD

**Issue by csch0en** [xmltv-se/issues#42]
Hi.

At https://xmltv.xmltv.se, in ALL channel .xml and .gz files there is data missing after the date 27.sept.
This problem exists since a few days. Timestamp of all the files is 23-sept-2020.
They all have only 140/142 bytes.
Is there something going wrong?

BR.

**Comment by jnylen** [comment]
Read #21

**Comment by csch0en** [comment]
Thank you for this information. 

BR.
