### ISSUE TITLE
Login to get one week data

### ISSUE THREAD

**Issue by hallonstedt** [xmltv-se/issues#43]
I get the problem with commercial misuse of the data you are producing but three days is not very practical when scheduling recordings and keeping track of upcoming recordings. 

In the pinned #[issue ](https://github.com/pixelmonster-ou/xmltv.se/issues/21#issue-612087542)where you informed about the reduction to three days, you also open up for logging in or in other ways identifying yourself for the ability to retrieve more data. Would you kindly let us know if this is in progress?

If you need any help, I am sure the community is willing to assist. Me included!

**Comment by jnylen** [comment]
Hi @hallonstedt,

> I get the problem with commercial misuse of the data you are producing but three days is not very practical when scheduling recordings and keeping track of upcoming recordings.

There are 14 days available on Honeybee.

> In the pinned #issue where you informed about the reduction to three days, you also open up for logging in or in other ways identifying yourself for the ability to retrieve more data. Would you kindly let us know if this is in progress?

Currently there is no planned change regarding that. I'm too busy with fixing Honeybee and other real life stuff.

> If you need any help, I am sure the community is willing to assist. Me included!

Sadly I haven't had any help with this for the 10 years I have been managing XMLTV.se (and the other names of it) so I don't believe other people would help in this regard.
