### ISSUE TITLE
Honeybee sample?

### ISSUE THREAD

**Issue by JD906** [xmltv-se/issues#45]
Hi.

Since you limited your data to 3 days, and now all tv-shows are missing season number and episode number, its getting at bit hard to keep track of everything.
On Honeybee.it/xmltv there is at button for getting a sample, but it doesn't work.
I would like to see the data, before paying for a year.
Is that possible?

Regards.

**Comment by jnylen** [comment]
@JD906
Sorry for the extremly late answer here. Please email the email address in the footer of the website for a sample. This issue tracking is for a seperate project.
