### ISSUE TITLE
Season and Episode number missing in data

### ISSUE THREAD

**Issue by svallebro** [xmltv-se/issues#46]
**Channel svt1.svt.se**
**Channel svt2.svt.se**
**Channel tv3.se**
**Channel tv4.se**
**Channel kanal5.se**
**Channel tv6.se**
**Channel sjuan.se**
**Channel tv8.se**
**Channel kanal9.se**
**Channel tv10.se**
**Channel tv11.sbstv.se**
**Channel tv12.tv4.se**

Is this the way it supposed to be in the future, after the restrictions to three days of available files?

**Comment by jnylen** [comment]
Hi,
Yes. The data provided for free is gonna be basic. Which means title and descriptions.
