### ISSUE TITLE
Episode numbers missing from 2020-09-23 and after

### ISSUE THREAD

**Issue by erkswede** [xmltv-se/issues#47]
**Channel XMLTV ID**

Multiple channels, SVT1, SVT2, TV3, TV4 etc.

**Specific date**

From 2020-09-23 and every day after.

Running: tv_grab_eu_xmltvse --config-file <config file for sweden, all channels>
No data for episode numbers are present in the XML returned

I observed this issue inside Mythtv 0.29 when certain episodes didn't record as expected and other episodes was recorded over and over again. In mythtv it's possible to view all data for a recording or programguide listing by pressing "i". From 2020-09-23 there is no episode data displayed. Before 2020-09-23 there is episode data present. Nothing is changed in my system around that time.

Trying to resolve this I have installed xmltv 0.6.1 but that didn't help. Same behavior with xmltv 0.5.7 and tv_grab_se_swedb.

**Comment by jnylen** [comment]
Please look at other issues before creating a duplicate one.
