### ISSUE TITLE
xmltv.exe Failed to fetch

### ISSUE THREAD

**Issue by Raven-71** [xmltv-se/issues#50]
c:\>xmltv.exe tv_grab_eu_xmltvse --days 14 --output "C:\tv_output.xml"
Timezone is +0200
Failed to fetch http://xmltv.xmltv.se/channels-Sweden.xml.gz at /<c:\>grab/eu_xmltvse/tv_grab_eu_xmltvse line 400.

c:\>xmltv.exe tv_grab_eu_xmltvse --version
Timezone is +0200
XMLTV module version 0.6.1
This is tv_grab_eu_xmltvse version 0.6.1

To old xmltv.exe!? this is the latest windows "pre-built binary" from https://github.com/XMLTV/xmltv

**Comment by JD906** [comment]
Try changing http to https in url.

**Comment by Raven-71** [comment]
how do i change/configure the xmltv.exe(windows) to use https instead of http?

**Comment by JD906** [comment]
I changed mine in the .conf file, in the xmltv folder.
http://xmltv.xmltv.se/channels-Sweden.xml.gz  to  https://xmltv.xmltv.se/channels-Sweden.xml.gz

**Comment by Raven-71** [comment]
In the old xmltv.exe Version 0.5.68 the first line in the .conf file is
root-url=http://xmltv.xmltv.se/channels.xml.gz

But in the 0.6.1 there is no such line (instead country=Sweden). And if i add the "root-url=https://xmltv.xmltv.se/channels-Sweden.xml.gz" line, it it just seems to concatenate the 2 addresses to:

Failed to fetch http://xmltv.xmltv.se/channels-https://xmltv.xmltv.se/channels-Sweden.xml.gz.xml.gz at /<c:\xmltv.exe>grab/eu_x
mltvse/tv_grab_eu_xmltvse line 400.

so it might be hard coded in version 0.6.1...

**Comment by jnylen** [comment]
@JD906 I have opened a PR to update it to SSL in the config. Thanks for reminding me.

**Comment by jnylen** [comment]
@Raven-71 I have disabled Force SSL for now until XMLTV releases the version with the fix which I assume will be in 2022.

**Comment by Raven-71** [comment]
Thanks!
Now it works again.
so the problem is not that i am running 0.6.1 since there is no link to download 0.6.3?
