### ISSUE TITLE
berl.rbb-online.de is behind by 2 hours, even after correcting for local timezone

### ISSUE THREAD

**Issue by joshinils** [xmltv-se/issues#51]
**Channel XMLTV ID**

berl.rbb-online.de

**Example**
today (2020-10-22 in Berlin, Germany, local time) the program for RBB Berlin starts with:
```xml
  <programme channel="berl.rbb-online.de" start="20201022040000 +0000" stop="20201022050000 +0000">
    <title lang="de">zibb</title>
    <category lang="en">series</category>
  </programme>
```
The time is wrong by 2 hours, for all of rbb.
however, after correcting it to my local timezone, meaning add 2 hours, it is still behind by 2 hours.

see the correct program here:
https://www.rbb-online.de/fernsehen/programm/

I generate a tv guide for home use with: https://github.com/joshinils/tv/
so any channels in there get the same treatment of timezone correction, ard and zdf, for example, are correct, rbb is the only one which is wrong like that (I checked all the channels I am interested in which have data today)

I want to apologise for not using the [datalist](https://xmltv.xmltv.se/datalist.xml.gz), I did not know of it until today

**Comment by jnylen** [comment]
@joshinils Good catch i'll look into it on Sunday.

**Comment by jnylen** [comment]
This should be done by now.

**Comment by joshinils** [comment]
I'm afraid not for me, the data I get is ahead by one hour. :roll_eyes: 
I have not implemented any special case for rbb, so that can't be it now.

summertime ended since I posted this btw. on 25. Oktober.

**Comment by jnylen** [comment]
@joshinils 
The Berlin and Brandenburg channels will have correct data tomorrow.
I'm considering removing the `gemeinsamt` variant as that doesn't seem to exist anymore.

Please get back to me tomorrow if the data is correct or not.

**Comment by joshinils** [comment]
ehm, weirdly enough: sometimes... 
it starts off good at 6:00 but every day there should be "tagesschau" at 20:00-20:15, which isnt the case on the 12th, but is correct on the 11th and 13th, i'm also terribly confused why some proigrams appear correctly and others do not, or have the wrong time or are just the wrong one..
in any case it is better than before.

**Comment by jnylen** [comment]
@joshinils how about now?

**Comment by joshinils** [comment]
as much the same as i would expect, very good.
the few differences are probably down to this being the local variant of rbb. but aside from that (which is probably good), most of the programs are the same with the same times (escpecially some series with episode numbers, so i'm rather sure about it).

**Comment by jnylen** [comment]
@joshinils how, closing this then 🙂
