### ISSUE TITLE
most german private channels don't have a description for anything

### ISSUE THREAD

**Issue by joshinils** [xmltv-se/issues#52]
**Channel XMLTV ID**
this includes, but may not be limited to:
- sat1.se
- rtl.de
- prosieben.de
- kabel1.de
- vox.de
- super.rtl.de
- sixx.de
- rtl2.de
- n-tv.de

**Comment by joshinils** [comment]
the data is correct, it is just always missing a description, which I find weird.

**Comment by jnylen** [comment]
It's because of how German TV channels forces everyone to license the use of their images and texts.

Nothing i can do unless I start paying VGMedia x amount per user + channel amount.

You can find a list here
https://www.vg-media.de/en/right-holders.html

Prosieben has their own variant of it.

**Comment by joshinils** [comment]
I see, so a program-magazine I can buy like hoerzu or tvspielfilm has paid that, even for the online version. but scraping from the channels website would be a no-no.

**Comment by jnylen** [comment]
Yes.
We have signed or written agreements for all channels. We don't scrape websites unless given an OK by them.

For example Prosieben sends us the data by ftp without the descriptions so we can't add that anyway.

Also, so you know. You're not allowed to have the data XMLTV.se produce on a public website. Only for private use.

So don't put that tvguide python project up on the web 🙂

**Comment by joshinils** [comment]
yes, never intend to do so, currently hosted on a raspi which is very nice since it already hosts a pi-hole where I can sneakily put an html file that also gets hosted in my lan.

besides, anyone could use my code and host it, but then it's not me hosting it
