### ISSUE TITLE
No data for any channels today and forward

### ISSUE THREAD

**Issue by Asger-P** [xmltv-se/issues#54]
There is no channel data for any of these channels today ( 2020-11-07 ) and the next days:
http://xmltv.xmltv.se/dr1.dr.dk_2020-11-07.xml
http://xmltv.xmltv.se/dr2.dr.dk_2020-11-07.xml
http://xmltv.xmltv.se/charlie.tv2.dk_2020-11-07.xml
http://xmltv.xmltv.se/fri.tv2.dk_2020-11-07.xml
http://xmltv.xmltv.se/news.tv2.dk_2020-11-07.xml
http://xmltv.xmltv.se/tv2.dk_2020-11-07.xml
http://xmltv.xmltv.se/zulu.tv2.dk_2020-11-07.xml

From what I can see does this have effect for all channels.

**Comment by jnylen** [comment]
No need to create another issue when there is already #53. Please look at other issues before create duplicates.
