### ISSUE TITLE
No data for e.g. zdf.de on 2020.11.07

### ISSUE THREAD

**Issue by Chris56** [xmltv-se/issues#55]
zdf.de and other german channels
Despite the list here:
https://xmltv.xmltv.se/00index.html

which claims that there is data for e.g. zdf.de on the 7. November 2020 and 8. Novemvber 2020

the output of tv_grab_eu_xmltvse only starts on the 9th of Novemeber.

This seem to be true at least for all german stations.
Chris
P.S.: I do see entries for the 9th onwards ...

**Comment by jnylen** [comment]
No need to create another issue when there is already #53. Please look at other issues before create duplicates.
