### ISSUE TITLE
json.xmltv.se down?

### ISSUE THREAD

**Issue by psqv** [xmltv-se/issues#60]
Is json.xmltv.se down or has the url scheme for the json data been changed?

I was using it in a private project, but it seems like i get no data when I poll  (as an example) http://json.xmltv.se/kunskapskanalen.svt.se_2021-02-07.js.gz which used to work just fine.

Please let me know if i need to switch over to an XML parser instead.

**Comment by jnylen** [comment]
Hi @psqv,

That url has been down since 2019-ish and is not coming back due to abuse from companies that were more willing to use that data than supporting the maintenance of it.
