### ISSUE TITLE
hd.tv4.se has data up to yesterday

### ISSUE THREAD

**Issue by motoz** [xmltv-se/issues#64]
**hd.tv4.se*

It has been missing data 'today' for several days. It seems to update daily so 'yesterday' is always ok.

Today (2021-03-26) http://xmltv.xmltv.se/hd.tv4.se_2021-03-25.xml has data and http://xmltv.xmltv.se/hd.tv4.se_2021-03-26.xml and forward is empty.

**Comment by jnylen** [comment]
Hi @motoz,

Data is provided as is. You can get stable data through honeybee.

**Comment by motoz** [comment]
I'm aware of that, thanks for the service.
