### ISSUE TITLE
ORF Austria missing data

### ISSUE THREAD

**Issue by csch0en** [xmltv-se/issues#66]
I suspect the following problem :

orf1.orf.at - complete missing data
orf2.orf.at - fragmented data
orf3.orf.at - fragmented data

since a few days

BR.

**Comment by jnylen** [comment]
Hi @csch0en,

Issue was of the internal cronjob not scheduling the jobs for all different underlying processes (each running in a seperate Erlang process) not being queued with a background job. I enqueued this manually now and will post a fix so they will be run.

I'll also look into some failsafes to make sure these are enqueued and add some alerts to different parts for the coming weeks.

The ORF channels should have data soon as I needed to enqueue 3 jobs per channel.

**Comment by csch0en** [comment]
Hi.
Best thanks for your effort.

BR.
