### ISSUE TITLE
Fragmented Data ORF Austria

### ISSUE THREAD

**Issue by csch0en** [xmltv-se/issues#69]
orf1.orf.at
orf3.orf.at

Sorry, but yet again fragmented data.
BR.

**Comment by jnylen** [comment]
Hi @csch0en<
Sorry for the delay here. Been a busy few weeks.

I'll take a look tomorrow/this weekend and see what it is. Sometimes these tiny issues are hard to track down.

**Comment by jnylen** [comment]
@csch0en,

Should be fixed since a few days ago.

**Comment by csch0en** [comment]
Hi.
It looks good and solved.
Very Thanks.
BR.
