### ISSUE TITLE
Most channels got only 2 days of data

### ISSUE THREAD

**Issue by TobbeJ** [xmltv-se/issues#78]
**Channel XMLTV ID**

For example svt1hd

**Specific date**

Only today and tomorrows data is there but if you look at the overview page on:
https://xmltv.xmltv.se/00index.html
there seems to be data for future dates too but this is not the case

**Example**

See above, only 2 days of data.
i believe this applies to other channels as well but not 100% sure

**Comment by jnylen** [comment]
@TobbeJ 

https://github.com/pixelmonster-ou/xmltv.se/issues/21

No promises of exactly 3 days of data. The data is provided AS IS with no guarantees of 3 days.
