### ISSUE TITLE
Phoenixhd no data

### ISSUE THREAD

**Issue by Chris56** [xmltv-se/issues#80]
phoenixhd.daserste.de is empty

However
phoenixhd and phoenix are generally identical and 
phoenix.daserste.de is all fine.
So you wouldn't really need both.

**Comment by Chris56** [comment]
It's ok now!

**Comment by jnylen** [comment]
Hi,

Phoenix HD copies the data from Phoenix and just adds HD as the quality.

And XMLTV.se isn't supported more than AS IS. If you want stable data Honeybee.it is the one.

**Comment by Chris56** [comment]
So - different from the past - I shall not report any broken data? Very important to know as it will save wasted effort.
Then - of course - it would make sense to NOT offer
Faulty Data
Missing Data
when reporting an issue.
Rather inform people not to report.

**Comment by jnylen** [comment]
@Chris56,

No it's correct to still report it. What I meant is that if you want stable data then you can use Honeybee.it.

Sorry if that came out wrong.
