### ISSUE TITLE
hd.tv4.se is empty

### ISSUE THREAD

**Issue by motoz** [xmltv-se/issues#82]
**hd.tv4.se**

Is missing all data.

**Comment by jnylen** [comment]
@motoz ill have a look later today, but xmltv.se is not as supported as honeybee. Honeybee still have data.

**Comment by motoz** [comment]
Great! I would gladly pay for access to honeybee data but I'm very averse to authorizing anyone to just grab money from my account, so for me there is sadly no suitable payment method.

**Comment by jnylen** [comment]
@motoz there is a way to pay by bank transfer, would that work?

**Comment by motoz** [comment]
That would be great! I'm unable to figure out how though, I'll try the support email (again :-) )

**Comment by motoz** [comment]
hd.tv4.se is working again, and I have a one year subscription to honeybee. Let's see if I ever figure out how to use that together with mythtv...

**Comment by motoz** [comment]
And now it's broken again...

**Comment by motoz** [comment]
working again...
